"""added app_notifications table

Revision ID: 2f2596740ebd
Revises: f6e4a395e346
Create Date: 2026-02-26 05:59:42.843951+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2f2596740ebd'
down_revision: Union[str, None] = 'f6e4a395e346'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_notifications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('vendor_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.String(length=50), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_notifications_tenant', 'app_notifications', ['tenant_id'], unique=False)
    op.create_index('idx_notifications_user', 'app_notifications', ['user_id'], unique=False)
    op.create_index('idx_notifications_vendor', 'app_notifications', ['vendor_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_notifications_vendor', table_name='app_notifications')
    op.drop_index('idx_notifications_user', table_name='app_notifications')
    op.drop_index('idx_notifications_tenant', table_name='app_notifications')
    op.drop_table('app_notifications')
    # ### end Alembic commands ###
