"""add document key to receipts

Revision ID: 41cdfa8bf366
Revises: c9e1f2a3b4d5
Create Date: 2026-02-23 16:07:56.985108+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '41cdfa8bf366'
down_revision: Union[str, None] = 'c9e1f2a3b4d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_approvals_user_status', table_name='approvals')
    op.drop_index('idx_budget_reservations_budget_status', table_name='budget_reservations')
    op.drop_index('idx_budgets_dept_year_quarter', table_name='budgets')
    op.drop_index('idx_invoices_match_status', table_name='invoices')
    op.drop_index('idx_invoices_vendor_status', table_name='invoices')
    op.drop_index('idx_po_status_delivery', table_name='purchase_orders')
    op.drop_index('idx_pr_dept_status', table_name='purchase_requests')
    op.drop_index('idx_pr_tenant_status_date', table_name='purchase_requests')
    op.add_column('receipts', sa.Column('document_key', sa.String(length=255), nullable=True))
    op.drop_index('idx_users_email_active', table_name='users', postgresql_where='(deleted_at IS NULL)')
    op.drop_index('idx_vendors_name_trgm', table_name='vendors', postgresql_using='gin')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_vendors_name_trgm', 'vendors', ['legal_name'], unique=False, postgresql_using='gin')
    op.create_index('idx_users_email_active', 'users', ['email', 'is_active'], unique=False, postgresql_where='(deleted_at IS NULL)')
    op.drop_column('receipts', 'document_key')
    op.create_index('idx_pr_tenant_status_date', 'purchase_requests', ['tenant_id', 'status', sa.text('created_at DESC')], unique=False)
    op.create_index('idx_pr_dept_status', 'purchase_requests', ['department_id', 'status'], unique=False)
    op.create_index('idx_po_status_delivery', 'purchase_orders', ['status', 'expected_delivery_date'], unique=False)
    op.create_index('idx_invoices_vendor_status', 'invoices', ['vendor_id', 'status'], unique=False)
    op.create_index('idx_invoices_match_status', 'invoices', ['match_status', sa.text('created_at DESC')], unique=False)
    op.create_index('idx_budgets_dept_year_quarter', 'budgets', ['department_id', 'fiscal_year', 'quarter'], unique=False)
    op.create_index('idx_budget_reservations_budget_status', 'budget_reservations', ['budget_id', 'status'], unique=False)
    op.create_index('idx_approvals_user_status', 'approvals', ['approver_id', 'status', sa.text('created_at DESC')], unique=False)
    # ### end Alembic commands ###
