"""make_contract_vendor_id_nullable_and_add_association_table

Revision ID: 93d70dd64a63
Revises: 2f2596740ebd
Create Date: 2026-02-26 06:30:05.814875+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '93d70dd64a63'
down_revision: Union[str, None] = '2f2596740ebd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contract_vendors',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('contract_id', sa.UUID(), nullable=False),
    sa.Column('vendor_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('assigned_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_contract_vendors_contract', 'contract_vendors', ['contract_id'], unique=False)
    op.create_index('idx_contract_vendors_tenant', 'contract_vendors', ['tenant_id'], unique=False)
    op.create_index('idx_contract_vendors_vendor', 'contract_vendors', ['vendor_id'], unique=False)
    op.alter_column('contracts', 'vendor_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('contracts', 'vendor_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_index('idx_contract_vendors_vendor', table_name='contract_vendors')
    op.drop_index('idx_contract_vendors_tenant', table_name='contract_vendors')
    op.drop_index('idx_contract_vendors_contract', table_name='contract_vendors')
    op.drop_table('contract_vendors')
    # ### end Alembic commands ###
