"""add_department_name_unique_constraint

Revision ID: f6e4a395e346
Revises: 28f19ed1d2d4
Create Date: 2026-02-24 09:08:57.146179+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f6e4a395e346'
down_revision: Union[str, None] = '28f19ed1d2d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Remove duplicate department rows (keep the one with the smallest ctid per tenant+name).
    # Must delete child budgets first to avoid FK violation.
    conn = op.get_bind()

    # 1. Delete budgets belonging to duplicate departments (not the one we'll keep)
    conn.execute(sa.text("""
        DELETE FROM budgets
        WHERE department_id IN (
            SELECT id FROM departments
            WHERE ctid NOT IN (
                SELECT min(ctid)
                FROM departments
                GROUP BY tenant_id, name
            )
        )
    """))

    # 2. Now delete the duplicate department rows
    conn.execute(sa.text("""
        DELETE FROM departments
        WHERE ctid NOT IN (
            SELECT min(ctid)
            FROM departments
            GROUP BY tenant_id, name
        )
    """))
    op.create_unique_constraint('uq_department_tenant_name', 'departments', ['tenant_id', 'name'])


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_department_tenant_name', 'departments', type_='unique')
    # ### end Alembic commands ###
